### ISSUE TITLE
Prepare internationalization and localization

### ISSUE THREAD

**Issue by andrewerlanger** [andrewerlanger/aestival#12]
Aestival currently is only available in German. But this will not always be the case. 

Knowing that we want to offer the site in English in the not-too-distant future, we should already lay the groundwork for i18n.

These guides seem quite useful as a starting point:
[https://docs.djangoproject.com/en/2.2/topics/i18n/](https://docs.djangoproject.com/en/2.2/topics/i18n/)
[https://phrase.com/blog/posts/quick-guide-django-i18n/](https://phrase.com/blog/posts/quick-guide-django-i18n/)

In the end, we want to be able to load the text into our templates like this:
```
{% load i18n %}
 
<h1>{% translate 'WelcomeHeading' %}</h1>
```

**Comment by trodellez** [comment]
added language files and changed template accordingly for main app
